apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ceph-bucket
spec:
  generateBucketName: demo-bucket
  storageClassName: ocs-storagecluster-ceph-rgw
  additionalConfig:
    maxObjects: "1000"
    maxSize: "2G"
